// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://erhzxzjwhaongbtrcyib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVyaHp4emp3aGFvbmdidHJjeWliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMDM5MzAsImV4cCI6MjA1ODU3OTkzMH0.2O5_bBtaCOQjVYC-MSxTKP3CZJ4J7Z1_OeSN4mS31Ko";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);